#!/usr/bin/env bash
usage () {
    cat <<HELP_USAGE
    backup host:port user:pwd target delay
HELP_USAGE
}
if [[ ($3) && $3 == "usage" ]]; then
    usage
    exit 255
fi
if [[ (-z "$4") ]]; then
    sh cmds/errors/generic
    exit $?
fi

curl -w "%{http_code}\n"  -o /dev/null -isf -k -u $2 http://$1/libs/granite/backup/content/createBackup/content/items/backupform.html -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' --data 'force=true&target='$3'&delay='$4 