#!/usr/bin/env bash
usage () {
    cat <<HELP_USAGE
    user host:port user:pwd [enable|changepwd] userid [password_to_change]
HELP_USAGE
}

if [[ (-z "$3")  || ($3 -ne "enable" && $3 -ne "changepwd") || (-z "$4") ]]; then
    sh cmds/errors/generic $(usage)
    exit $?
fi
if [ $3 == "enable" ]; then
    curl -w "%{http_code}\n" -o /dev/null -is -k -u $2 http://$1/home/users/system/$4.rw.html -X POST -F disableUser= 
fi
if [ $3 == "changepwd" ]; then
    IFS=':' read -r -a PARAMS <<< "$2"
    curl -w "%{http_code}\n" -o /dev/null -is -k -u $2 http://$1/home/users/system/$4.rw.userprops.html -X POST -F :currentPassword=${PARAMS[1]} -F rep:password=$5
fi
#rc=$?; if [[ $rc != 200 ]]; then exit 1; fi
 
